# --- ГЛОБАЛЬНАЯ КОНФИГУРАЦИЯ ---

# Укажите АБСОЛЮТНЫЙ путь к вашему хранилищу Obsidian. 
# Скрипт автоматически обработает путь, поэтому можно использовать как прямые (/), так и обратные (\) слэши.
vault_path: 'D:\dkosarevmusicPOLYGON'